name: Server Heartbeat

on:
  schedule:
    - cron: '0 0 * * *'  # 每天定时触发，可以根据需要调整定时表达式
  workflow_dispatch:  # 允许手动触发

jobs:
  server-login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install sshpass
        run: sudo apt-get install sshpass  # 安装 sshpass 工具

      - name: Run SSH Login Script
        env:
          SERVER_CREDENTIALS: ${{ secrets.SERVER_CREDENTIALS }}  # 从Secrets中加载服务器信息
        run: |
          # 解析 JSON 格式的服务器信息
          echo "Parsing server credentials"
          SERVER_JSON=$(echo $SERVER_CREDENTIALS | jq -r 'to_entries | .[] | "Host: \(.key), IP: \(.value.host), User: \(.value.username), Password: \(.value.password)"')
          
          for server in $SERVER_JSON; do
            SERVER_NAME=$(echo $server | awk -F, '{print $1}' | cut -d' ' -f2)
            SERVER_IP=$(echo $server | awk -F, '{print $2}' | cut -d' ' -f3)
            SERVER_USER=$(echo $server | awk -F, '{print $3}' | cut -d' ' -f2)
            SERVER_PASS=$(echo $server | awk -F, '{print $4}' | cut -d' ' -f3)

            echo "Logging in to $SERVER_NAME ($SERVER_IP) as $SERVER_USER"
            
            # 使用 sshpass 通过密码登录
            sshpass -p "$SERVER_PASS" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "echo 'Server is alive at $(date)'"
          done
