name: Server Heartbeat

on:
  schedule:
    - cron: '0 0 * * *'  # 每天定时触发，可以根据需要调整定时表达式
  workflow_dispatch:  # 允许手动触发

jobs:
  server-login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # 您的私钥存储在GitHub Secrets中

      - name: Run SSH Login Script
        env:
          SERVER_CREDENTIALS: ${{ secrets.SERVER_CREDENTIALS }}  # 从Secrets中加载服务器信息
        run: |
          # 解析 JSON 格式的服务器信息
          echo "Parsing server credentials"
          SERVER_JSON=$(echo $SERVER_CREDENTIALS | jq -r 'to_entries | .[] | "Host: \(.key), IP: \(.value.host), User: \(.value.username)"')
          
          for server in $SERVER_JSON; do
            SERVER_NAME=$(echo $server | awk -F, '{print $1}' | cut -d' ' -f2)
            SERVER_IP=$(echo $server | awk -F, '{print $2}' | cut -d' ' -f3)
            SERVER_USER=$(echo $server | awk -F, '{print $3}' | cut -d' ' -f2)

            echo "Logging in to $SERVER_NAME ($SERVER_IP) as $SERVER_USER"
            ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "echo 'Server is alive at $(date)'"
          done
